import { mockTests } from "./mock-tests-data.js";
import { auth, db } from "../js/firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { doc, getDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const list = document.querySelector("#mockTestsList"), detail = document.querySelector("#mockTestDetail"), status = document.querySelector("#accessStatus"), telegramLink = document.querySelector("#telegramAccessLink");
function renderTestCards() { list.replaceChildren(...mockTests.map((test) => { const button = document.createElement("button"); button.className = "mock-card"; button.type = "button"; button.innerHTML = `<span class="mock-card__number">${String(test.id).padStart(2, "0")}</span><h2>${test.title}</h2><p>45 ta savol</p><span>PDF + 9 ta video yechim →</span>`; button.addEventListener("click", () => showTest(test.id)); return button; })); }
function showTest(id) { const test = mockTests.find((item) => item.id === id); if (!test) return; detail.replaceChildren(); const heading = document.createElement("h2"); heading.textContent = test.title.toUpperCase(); const pdfSection = document.createElement("section"); pdfSection.className = "pdf-section"; pdfSection.innerHTML = "<h3>📄 Test varianti</h3><p>45 ta savoldan iborat test variantini PDF shaklida oching.</p>"; const pdfLink = document.createElement("a"); pdfLink.className = "primary-button"; pdfLink.href = test.pdf; pdfLink.target = "_blank"; pdfLink.rel = "noopener noreferrer"; pdfLink.textContent = "PDF testni ochish"; pdfSection.append(pdfLink); const videoHeading = document.createElement("h3"); videoHeading.className = "video-heading"; videoHeading.textContent = "🎥 Video yechimlar"; const videos = document.createElement("div"); videos.className = "video-grid"; test.videos.forEach((video) => { const card = document.createElement("article"); card.className = "video-card"; const title = document.createElement("h4"); title.textContent = video.title; const frame = document.createElement("iframe"); frame.src = `https://www.youtube-nocookie.com/embed/${video.youtubeId}`; frame.title = `${test.title}: ${video.title}`; frame.loading = "lazy"; frame.allow = "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"; frame.allowFullscreen = true; card.append(title, frame); videos.append(card); }); detail.append(heading, pdfSection, videoHeading, videos); detail.hidden = false; detail.scrollIntoView({ behavior: "smooth", block: "start" }); }
async function checkAccess(user) { if (!user) return false; const profile = await getDoc(doc(db, "users", user.uid)); return profile.exists() && profile.data()?.mockTestsAccess === true; }
onAuthStateChanged(auth, async (user) => { try { if (!(await checkAccess(user))) { status.textContent = user ? "Bu bo‘lim uchun sizda ruxsat mavjud emas." : "Mock testlarni ko‘rish uchun tizimga kiring."; telegramLink.hidden = false; return; } status.remove(); document.querySelector("#protectedContent").hidden = false; renderTestCards(); } catch (error) { console.error("Mock testlar ruxsatini tekshirib bo‘lmadi:", error); status.textContent = "Ruxsatni tekshirib bo‘lmadi. Iltimos, keyinroq urinib ko‘ring."; } });
